version: '3'

services:
   app:  &python
      build: 
         context: .
         dockerfile: docker/app/Dockerfile
      image: nunki_demo_dev_image_internal
      container_name: nunki_demo_dev_internal

      restart: always
      ports:
         - '8089:8089'
      volumes:
         - ./:/app
      environment:
         - PYTHONUNBUFFERED=1
      command: bash -c "python3 /app/manage.py makemigrations && python3 /app/manage.py migrate && python3 /app/manage.py runserver 0.0.0.0:8089"

      # Testing debug mode in development environment
      # runserver --insecure
      # command: bash -c "python3 /app/manage.py makemigrations && python3 /app/manage.py migrate && python3 /app/manage.py runserver --insecure 0.0.0.0:8089"

      deploy:
         resources:
           limits:
             memory: 8G



